{% set version = "1.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tigris
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tigris_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tigris/tigris_{{ version }}.tar.gz
  sha256: 4924e6d4db15190c1ea9e3a24f0cb550c0f36a7c8551d7d4d329275ff4803db6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-magrittr
    - r-maptools
    - r-rappdirs
    - r-rgdal
    - r-sf
    - r-sp
    - r-stringr
    - r-uuid
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-magrittr
    - r-maptools
    - r-rappdirs
    - r-rgdal
    - r-sf
    - r-sp
    - r-stringr
    - r-uuid

test:
  commands:
    - $R -e "library('tigris')"           # [not win]
    - "\"%R%\" -e \"library('tigris')\""  # [win]

about:
  home: https://github.com/walkerke/tigris
  license: MIT
  summary: Download TIGER/Line shapefiles from the United States Census Bureau (<https://www.census.gov/geo/maps-data/data/tiger-line.html>) and load into R as 'sf' objects.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn

# Package: tigris
# Type: Package
# Title: Load Census TIGER/Line Shapefiles
# Version: 1.0
# Date: 2020-07-13
# Authors@R: c( person(given="Kyle", family="Walker", email="kyle@walker-data.com", role=c("aut", "cre")), person(given="Bob", family="Rudis", email="bob@rudis.net", role="ctb") )
# URL: https://github.com/walkerke/tigris
# BugReports: https://github.com/walkerke/tigris/issues
# Description: Download TIGER/Line shapefiles from the United States Census Bureau (<https://www.census.gov/geo/maps-data/data/tiger-line.html>) and load into R as 'sf' objects.
# License: MIT + file LICENSE
# LazyData: TRUE
# Encoding: UTF-8
# Depends: R (>= 3.3.0)
# Suggests: testthat, ggplot2, ggthemes, leaflet, knitr, rgeos
# Imports: stringr, magrittr, rgdal, sp, utils, rappdirs, maptools, httr, uuid, sf, dplyr, methods
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-07-13 10:42:29 UTC; kyle
# Author: Kyle Walker [aut, cre], Bob Rudis [ctb]
# Maintainer: Kyle Walker <kyle@walker-data.com>
# Repository: CRAN
# Date/Publication: 2020-07-13 12:20:03 UTC
